package:
  name: sagemath-repl
  version: "10.2"
  top-level:
    - PUT_TOP_LEVEL_IMPORT_NAMES_HERE
source:
  url: https://files.pythonhosted.org/packages/3a/21/7277ed40c6199451187ed1bf09155c1c68bd0e7567e7fbd392982cdc2d1c/sagemath-repl-10.2.tar.gz
  sha256: 72c51d313b484ac204230167498a23eb5f41848cb5ba43558646a015cacbad2c
about:
  home: ""
  PyPI: https://pypi.org/project/sagemath-repl
  summary:
    "Sage: Open Source Mathematics Software: IPython kernel, Sage preparser,
    doctester"
  license: GNU General Public License (GPL) v2 or later
requirements:
  run:
    - sagemath-environment
