package:
  name: sagemath-repl
  version: 10.3rc0
  top-level:
    - sage
source:
  url: file:sagemath-repl-10.3rc0.tar.gz
  # url: https://files.pythonhosted.org/packages/3a/21/7277ed40c6199451187ed1bf09155c1c68bd0e7567e7fbd392982cdc2d1c/sagemath-repl-10.2.tar.gz
  # sha256: 72c51d313b484ac204230167498a23eb5f41848cb5ba43558646a015cacbad2c
  sha256: d8b4aaef63c581ab4caa1754cfa562950de1575c20cb1d6eb3a070edf3e0837d
about:
  home: ""
  PyPI: https://pypi.org/project/sagemath-repl
  summary:
    "Sage: Open Source Mathematics Software: IPython kernel, Sage preparser,
    doctester"
  license: GNU General Public License (GPL) v2 or later
requirements:
  run:
    - sagemath-environment
    - sagemath-objects
    - ipython
build:
  unvendor-tests: false
