package:
  name: ipython
  version: 8.21.0
  top-level:
    - IPython
source:
  # pure Python package, can switch to wheel after patch is upstreamed
  url: https://files.pythonhosted.org/packages/83/aa/6b5bd15d4914394a4f6bd5a4d88dee2d5ddd1b346b8b60fd9e735223a8ea/ipython-8.21.0.tar.gz
  sha256: 48fbc236fbe0e138b88773fa0437751f14c3645fb483f1d4c5dee58b37e5ce73
  patches:
    - patches/14316.patch
requirements:
  run:
    - asttokens
    - decorator
    - executing
    - prompt_toolkit
    - pure_eval
    - Pygments
    - six
    - stack_data
    - traitlets
    - sqlite3
    - wcwidth
about:
  home: https://ipython.org
  PyPI: https://pypi.org/project/ipython
  summary: "IPython: Productive Interactive Computing"
  license: BSD-3-Clause
